# Generated by Django 2.2 on 2021-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
